"""
Verify Pipeline Script

Loads data generated by the factory using the DataLoader to ensure compatibility.
"""
import sys
import os

# Ensure project root is on sys.path
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from pathlib import Path
from src.ml.training.data_loader import DataLoader

def main():
    data_dir = Path("lab/data/test_batch")
    if not data_dir.exists():
        print(f"Data directory {data_dir} does not exist. Run factory first.")
        return

    loader = DataLoader(data_dir)
    try:
        df = loader.load_archetypes(pattern="*.parquet")
        print(f"Successfully loaded {len(df)} rows.")
        print("Columns:", df.columns.tolist())
        print("\nSample Data:")
        print(df[['close', 'is_setup', 'outcome_r']].head())
        
        setup_count = df['is_setup'].sum()
        print(f"\nTotal setups found in loaded data: {setup_count}")
        
    except Exception as e:
        print(f"Failed to load data: {e}")

if __name__ == "__main__":
    main()
